"""Resume checker report as a PDF (A4 portrait)."""

import asyncio
import io
from datetime import datetime

from fastapi import APIRouter
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel
from reportlab.graphics.shapes import Drawing, Rect
from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.platypus import (
    HRFlowable,
    KeepTogether,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from interview_pdf import MARGIN, ST, W, P, color_for
from pdf_resume import NAVY, as_list, as_str, fmt
from report_pdf import GREEN, LINE, MUTED, RED, ZEBRA, hexof

router = APIRouter(prefix="/api/check")


def match_label(score) -> str:
    n = float(score or 0)
    if n >= 75:
        return "Strong match"
    if n >= 50:
        return "Moderate match"
    if n >= 30:
        return "Weak match"
    return "Poor match"


def bar(value, width=300, height=9):
    d = Drawing(width, height + 2)
    d.add(Rect(0, 1, width, height, fillColor=HexColor("#E3E8F0"), strokeColor=None))
    v = max(0, min(100, float(value or 0)))
    if v > 0:
        d.add(Rect(0, 1, width * v / 100, height, fillColor=HexColor(color_for(v)), strokeColor=None))
    return d


def score_row(label, value, note):
    t = Table([[P(fmt(label), "bold"), bar(value),
                Paragraph(f'<font color="{color_for(value)}"><b>{fmt(value)}</b></font>', ST["bold"])]],
              colWidths=[165, 300, W - 465])
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (2, 0), (2, 0), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 2), ("BOTTOMPADDING", (0, 0), (-1, -1), 1),
    ]))
    parts = [t]
    if as_str(note):
        parts.append(P(fmt(note), "small"))
    parts.append(Spacer(1, 5))
    return KeepTogether(parts)


def summary_boxes(overall, fit, strength):
    cells = [
        [Paragraph(f'<font color="{color_for(overall)}">{fmt(overall)}</font>', ST["big"]),
         P("Overall score (out of 100)", "bigl"), P(fmt(match_label(overall)), "rank")],
        [Paragraph(f'<font color="{color_for(fit)}">{fmt(fit)}</font>', ST["big"]),
         P("Job fit: this resume vs this job", "bigl")],
        [Paragraph(f'<font color="{color_for(strength)}">{fmt(strength)}</font>', ST["big"]),
         P("Resume strength: how well it is written", "bigl")],
    ]
    t = Table([cells], colWidths=[W * 0.38, W * 0.31, W * 0.31])
    t.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.8, LINE), ("INNERGRID", (0, 0), (-1, -1), 0.5, LINE),
        ("BACKGROUND", (0, 0), (-1, -1), ZEBRA), ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 10), ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
    ]))
    return t


def bullets(items, color_hex):
    return [Paragraph(f'<font color="{color_hex}"><b>-</b></font> {fmt(i)}', ST["body"]) for i in as_list(items)]


def skills_block(title, items, color_hex):
    items = [as_str(i) for i in as_list(items) if as_str(i)]
    text = ", ".join(items) if items else "none"
    return KeepTogether([
        P(f"{fmt(title)} ({len(items)})", "bold"),
        Paragraph(f'<font color="{color_hex}">{fmt(text)}</font>', ST["body"]),
        Spacer(1, 6),
    ])


def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawString(MARGIN, 18, "Generated by Resume AI. Scores are a guide: skills are detected from a built-in list of common skills.")
    canvas.drawRightString(A4[0] - MARGIN, 18, f"Page {doc.page}")
    canvas.restoreState()


def build_check_pdf(result: dict, job_title: str = "", file_name: str = "") -> bytes:
    scores = result.get("scores") if isinstance(result.get("scores"), dict) else {}
    bd = scores.get("breakdown") if isinstance(scores.get("breakdown"), dict) else {}

    def part(key):
        v = bd.get(key) if isinstance(bd.get(key), dict) else {}
        return v.get("score", 0), v.get("note", "")

    fit, fit_note = part("fit")
    exp, exp_note = part("experience")
    edu, edu_note = part("education")
    qual, qual_note = part("quality")
    overall, strength = scores.get("overall", 0), scores.get("strength", 0)

    sub = "  |  ".join(x for x in (as_str(file_name), ("For: " + as_str(job_title)) if as_str(job_title) else "",
                                   datetime.now().strftime("%d %B %Y")) if x)
    story = [P("Resume Check Report", "title"), P(fmt(sub), "sub"), Spacer(1, 4),
             HRFlowable(width="100%", thickness=1, color=NAVY, spaceAfter=10),
             summary_boxes(overall, fit, strength)]

    story.append(P("Score breakdown", "h2"))
    story.append(score_row("Job fit (this resume vs this job)", fit, fit_note))
    story.append(P(fmt(f"Resume strength: {strength} / 100 (does not depend on the job)"), "small"))
    story.append(Spacer(1, 4))
    story.append(score_row("Experience and projects", exp, exp_note))
    story.append(score_row("Education", edu, edu_note))
    story.append(score_row("Resume quality", qual, qual_note))

    story.append(P("Skills from the job description", "h2"))
    story.append(skills_block("Found in your resume", scores.get("matched_skills"), hexof(GREEN)))
    story.append(skills_block("Missing from your resume", scores.get("missing_skills"), hexof(RED)))

    if as_str(result.get("match_summary")):
        story += [P("Summary", "h2"), P(fmt(result.get("match_summary")), "body")]
    if as_list(result.get("strengths")):
        story += [P("Strengths", "h2")] + bullets(result.get("strengths"), hexof(GREEN))
    if as_list(result.get("weaknesses")):
        story += [P("Weaknesses", "h2")] + bullets(result.get("weaknesses"), hexof(RED))
    if as_list(result.get("suggestions")):
        story += [P("Suggestions to improve", "h2")]
        for i, s in enumerate(as_list(result.get("suggestions")), 1):
            story.append(Paragraph(f'<b>{i}.</b> {fmt(s)}', ST["body"]))
            story.append(Spacer(1, 2))
    if as_str(result.get("ai_error")):
        story += [P("AI feedback", "h2"),
                  P(fmt("The AI feedback was not available when this report was made, so only the computed scores are shown."), "body")]

    story.append(P("How the score is worked out", "h2"))
    story.append(P(fmt(
        "Overall = Job fit x (0.7 + 0.3 x Resume strength / 100). Job fit is the share of the skills in the job description "
        "that appear in your resume (soft skills such as teamwork count about a third as much). If the job description names "
        "fewer than 3 known skills, keyword overlap is used as well. Resume strength combines experience and projects "
        "(internships, action-verb bullets, numbers), education (degree and CGPA) and resume quality (contact details, "
        "standard sections, length, quantified results). Because job fit controls the result, a well-written resume still "
        "scores low for a job it does not match. The same resume and job description always give the same numbers."), "small"))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=MARGIN, rightMargin=MARGIN,
                            topMargin=MARGIN, bottomMargin=MARGIN + 6,
                            title="Resume Check Report", author="Resume AI")
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()


class CheckReportIn(BaseModel):
    result: dict
    job_title: str = ""
    file_name: str = ""


@router.post("/report")
async def check_report(body: CheckReportIn):
    try:
        data = await asyncio.to_thread(build_check_pdf, body.result, body.job_title[:100], body.file_name[:120])
    except Exception as e:
        return JSONResponse({"error": f"Could not build the resume report: {e}"}, status_code=500)
    return Response(content=data, media_type="application/pdf")