"""Builds a readable PDF shortlist report (A4 landscape) from the company ranking result."""

import asyncio
import io
from datetime import datetime

from fastapi import APIRouter
from fastapi.responses import JSONResponse, Response
from pydantic import BaseModel
from reportlab.lib.colors import HexColor, white
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    HRFlowable,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

from pdf_resume import NAVY, as_dicts, as_list, as_str, fmt

router = APIRouter(prefix="/api/company")

PAGE = landscape(A4)
MARGIN = 30
CONTENT_W = PAGE[0] - 2 * MARGIN  # about 782 points

GREEN = HexColor("#2E7D32")
AMBER = HexColor("#B26A00")
RED = HexColor("#B00020")
MUTED = HexColor("#666666")
ZEBRA = HexColor("#F3F6FA")
LINE = HexColor("#D5DBE5")


def hexof(color) -> str:
    return "#" + color.hexval()[2:]


def style(name, size=8.5, bold=False, italic=False, color="#111111", align=None, leading=None):
    font = "Helvetica-BoldOblique" if bold and italic else "Helvetica-Bold" if bold \
        else "Helvetica-Oblique" if italic else "Helvetica"
    kw = {"alignment": align} if align is not None else {}
    return ParagraphStyle(name, fontName=font, fontSize=size, leading=leading or size * 1.25,
                          textColor=HexColor(color), **kw)


ST = {
    "title": style("title", 22, bold=True, color="#1F3A5F", leading=26),
    "sub": style("sub", 10.5, color="#555555", leading=14),
    "h2": style("h2", 13, bold=True, color="#1F3A5F", leading=16),
    "cell": style("cell", 8.5),
    "cellb": style("cellb", 9, bold=True),
    "small": style("small", 7.5, color="#666666"),
    "head": style("head", 8.5, bold=True, color="#FFFFFF"),
    "note": style("note", 8, italic=True, color="#555555"),
    "stat_n": style("stat_n", 20, bold=True, color="#1F3A5F", align=TA_CENTER, leading=24),
    "stat_l": style("stat_l", 8.5, color="#555555", align=TA_CENTER),
    "flag": style("flag", 8, color="#8A6D00"),
    "reason": style("reason", 8.5, color="#B00020"),
}


def score_color(overall) -> str:
    try:
        n = float(overall)
    except (TypeError, ValueError):
        n = 0
    return hexof(GREEN if n >= 70 else AMBER if n >= 50 else RED)


def clip(text, n=70) -> str:
    text = as_str(text)
    return text if len(text) <= n else text[: n - 1] + "..."


def P(text, key="cell"):
    return Paragraph(text, ST[key])


def candidate_cell(c: dict):
    cells = [P(fmt(clip(c.get("name") or "Unknown")), "cellb")]
    if as_str(c.get("email")):
        cells.append(P(fmt(clip(c.get("email"), 45)), "small"))
    cells.append(P(fmt(clip(c.get("filename"), 45)), "small"))
    if c.get("cgpa") is not None:
        cells.append(P(fmt(f"CGPA {c.get('cgpa'):g}") if isinstance(c.get("cgpa"), (int, float))
                       else fmt("CGPA " + as_str(c.get("cgpa"))), "small"))
    return cells


def score_cell(c: dict):
    big_style = style("bigscore", 17, bold=True, color=score_color(c.get("overall")), leading=21)
    return [
        Paragraph(fmt(c.get("overall")), big_style),
        P(fmt(f"fit {c.get('fit')} | strength {c.get('strength')}"), "small"),
    ]


def skills_text(items, color_hex) -> Paragraph:
    items = [as_str(i) for i in as_list(items) if as_str(i)]
    if not items:
        return P("-", "small")
    return Paragraph(f'<font color="{color_hex}">{fmt(", ".join(items))}</font>', ST["cell"])


def base_table(rows, widths):
    t = Table(rows, colWidths=widths, repeatRows=1)
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), NAVY),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 6), ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 5), ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [white, ZEBRA]),
        ("LINEBELOW", (0, 1), (-1, -1), 0.4, LINE),
        ("BOX", (0, 0), (-1, -1), 0.6, LINE),
    ]))
    return t


def stat_box(number, label):
    t = Table([[P(fmt(number), "stat_n")], [P(fmt(label), "stat_l")]],
              colWidths=[CONTENT_W / 4 - 8])
    t.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.8, LINE),
        ("BACKGROUND", (0, 0), (-1, -1), ZEBRA),
        ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawString(MARGIN, 16, "Generated by Resume AI. Decision aid only: review resumes before deciding.")
    canvas.drawRightString(PAGE[0] - MARGIN, 16, f"Page {doc.page}")
    canvas.restoreState()


def build_report(result: dict, criteria: dict) -> bytes:
    candidates = as_dicts(result.get("candidates"))
    unreadable = as_dicts(result.get("unreadable"))
    summary = result.get("summary") if isinstance(result.get("summary"), dict) else {}
    selected = [c for c in candidates if c.get("selected")]
    rejected = [c for c in candidates if not c.get("selected")]

    job_title = as_str(criteria.get("job_title")) or "Job shortlist"
    story = []

    # ---- title ----
    story.append(P("Shortlist Report", "title"))
    story.append(P(fmt(f"{job_title}  |  {datetime.now().strftime('%d %B %Y')}"), "sub"))
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=1, color=NAVY, spaceAfter=10))

    # ---- stat boxes ----
    boxes = [
        stat_box(summary.get("total", len(candidates) + len(unreadable)), "Resumes uploaded"),
        stat_box(summary.get("shortlisted", len(selected)), "Shortlisted"),
        stat_box(summary.get("not_shortlisted", len(rejected)), "Not shortlisted"),
        stat_box(summary.get("unreadable", len(unreadable)), "Could not be read"),
    ]
    row = Table([boxes], colWidths=[CONTENT_W / 4] * 4)
    row.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"),
                             ("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 8)]))
    story.append(row)
    story.append(Spacer(1, 10))

    # ---- criteria ----
    jd_skills = ", ".join(as_str(s) for s in as_list(result.get("jd_skills"))) or "none detected"
    must = as_str(criteria.get("must_have")) or "none"
    min_score = as_str(criteria.get("min_score")) or "0"
    min_cgpa = as_str(criteria.get("min_cgpa")) or "0"
    story.append(P("Criteria used", "h2"))
    story.append(Spacer(1, 3))
    story.append(P(fmt(f"Skills found in the job description: {jd_skills}"), "cell"))
    story.append(P(fmt(f"Must-have skills: {must}   |   Minimum score: {min_score}   |   "
                       f"Minimum CGPA: {'ignored' if min_cgpa in ('0', '0.0') else min_cgpa}"), "cell"))
    if as_str(result.get("warning")):
        story.append(Spacer(1, 3))
        story.append(P(fmt(result.get("warning")), "note"))
    story.append(Spacer(1, 12))

    # ---- shortlisted ----
    story.append(P(fmt(f"Shortlisted ({len(selected)}), best first"), "h2"))
    story.append(Spacer(1, 4))
    if not selected:
        story.append(P("Nobody met all the conditions.", "cell"))
    else:
        rows = [[P(h, "head") for h in ("#", "Candidate", "Score", "Matched skills", "Missing skills", "Notes")]]
        for c in selected:
            notes = [P(fmt(f), "flag") for f in as_list(c.get("flags"))]
            if as_str(c.get("ai_summary")):
                notes.append(P(fmt(c.get("ai_summary")), "note"))
            rows.append([
                P(fmt(c.get("rank")), "cellb"),
                candidate_cell(c),
                score_cell(c),
                skills_text(c.get("matched_skills"), hexof(GREEN)),
                skills_text(c.get("missing_skills"), hexof(RED)),
                notes or P("-", "small"),
            ])
        story.append(base_table(rows, [24, 170, 74, 190, 130, CONTENT_W - 588]))
    story.append(Spacer(1, 14))

    # ---- not shortlisted ----
    if rejected:
        story.append(P(fmt(f"Not shortlisted ({len(rejected)})"), "h2"))
        story.append(Spacer(1, 4))
        rows = [[P(h, "head") for h in ("Candidate", "Score", "Missing skills", "Why not")]]
        for c in rejected:
            why = [P(fmt(r), "reason") for r in as_list(c.get("reasons"))]
            why += [P(fmt(f), "flag") for f in as_list(c.get("flags"))]
            rows.append([
                candidate_cell(c),
                score_cell(c),
                skills_text(c.get("missing_skills"), hexof(RED)),
                why or P("-", "small"),
            ])
        story.append(base_table(rows, [190, 74, 210, CONTENT_W - 474]))
        story.append(Spacer(1, 14))

    # ---- unreadable ----
    if unreadable:
        story.append(P(fmt(f"Could not be read ({len(unreadable)})"), "h2"))
        story.append(Spacer(1, 4))
        rows = [[P(h, "head") for h in ("File", "Reason")]]
        for u in unreadable:
            rows.append([P(fmt(clip(u.get("filename"), 80))), P(fmt(u.get("reason")))])
        story.append(base_table(rows, [300, CONTENT_W - 300]))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=PAGE,
        leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN, bottomMargin=MARGIN + 6,
        title="Shortlist Report - " + job_title, author="Resume AI",
    )
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()


class ReportIn(BaseModel):
    result: dict
    criteria: dict = {}


@router.post("/report")
async def report(body: ReportIn):
    try:
        data = await asyncio.to_thread(build_report, body.result, body.criteria)
    except Exception as e:
        return JSONResponse({"error": f"Could not build the report: {e}"}, status_code=500)
    return Response(content=data, media_type="application/pdf")