"""PDF report for the teacher project-report review (A4 landscape)."""

import io
from datetime import datetime

from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import HRFlowable, Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from pdf_resume import NAVY, as_dicts, as_list, as_str, fmt
from report_pdf import (
    AMBER,
    CONTENT_W,
    GREEN,
    MARGIN,
    MUTED,
    PAGE,
    RED,
    ST,
    P,
    base_table,
    clip,
    hexof,
    stat_box,
)


# headings stay on the same page as the table that follows them
H2K = ParagraphStyle("h2k", parent=ST["h2"], keepWithNext=1, spaceAfter=4)
NOTEK = ParagraphStyle("notek", parent=ST["note"], keepWithNext=1, spaceAfter=4)


def heading(text):
    return Paragraph(fmt(text), H2K)


def check_line(c: dict):
    res = as_str(c.get("result"))
    if res == "pass":
        tag = f'<font color="{hexof(GREEN)}"><b>Pass</b></font>'
    elif res == "fail":
        tag = f'<font color="{hexof(RED)}"><b>Fail</b></font>'
    else:
        tag = f'<font color="{hexof(AMBER)}"><b>Check</b></font>'
    text = f"{tag}  {fmt(c.get('label'))}"
    detail = as_str(c.get("detail"))
    if detail:
        if c.get("kind") == "ai" and res == "pass":
            text += f'<br/><font size="7.5" color="#666666"><i>Proof: "{fmt(clip(detail, 170))}"</i></font>'
        else:
            text += f" - {fmt(clip(detail, 170))}"
    return Paragraph(text, ST["cell"])


def note_line(note):
    return Paragraph(f'<font color="{hexof(AMBER)}"><b>Note</b></font>  {fmt(clip(note, 200))}', ST["cell"])


def student_cell(r: dict):
    cells = [P(fmt(clip(r.get("name") or "Unknown", 50)), "cellb")]
    if as_str(r.get("roll_no")):
        cells.append(P(fmt("Roll no: " + as_str(r.get("roll_no"))), "small"))
    cells.append(P(fmt(clip(r.get("filename"), 45)), "small"))
    return cells


def reports_table(records):
    rows = [[P(h, "head") for h in ("Student", "Pages", "Checks")]]
    for r in records:
        lines = [check_line(c) for c in as_dicts(r.get("checks"))]
        lines += [note_line(n) for n in as_list(r.get("notes"))]
        rows.append([student_cell(r), P(fmt(r.get("pages") or "-")), lines or P("-", "small")])
    return base_table(rows, [210, 50, CONTENT_W - 260])


def on_page(canvas, doc):
    canvas.saveState()
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(MUTED)
    canvas.drawString(MARGIN, 16, "Generated by Resume AI. Automatic checks are a decision aid: please verify before final approval.")
    canvas.drawRightString(PAGE[0] - MARGIN, 16, f"Page {doc.page}")
    canvas.restoreState()


def build_teacher_report(result: dict) -> bytes:
    reports = as_dicts(result.get("reports"))
    req = result.get("requirements") if isinstance(result.get("requirements"), dict) else {}
    approved = [r for r in reports if r.get("status") == "approved"]
    rejected = [r for r in reports if r.get("status") == "unapproved"]
    review = [r for r in reports if r.get("status") == "review"]

    assignment = as_str(req.get("assignment")) or "Project reports"
    story = []

    story.append(P("Project Report Review", "title"))
    story.append(P(fmt(f"{assignment}  |  {datetime.now().strftime('%d %B %Y')}"), "sub"))
    story.append(Spacer(1, 4))
    story.append(HRFlowable(width="100%", thickness=1, color=NAVY, spaceAfter=10))

    boxes = [
        stat_box(len(reports), "Reports uploaded"),
        stat_box(len(approved), "Approved"),
        stat_box(len(rejected), "Not approved"),
        stat_box(len(review), "Need manual review"),
    ]
    row = Table([boxes], colWidths=[CONTENT_W / 4] * 4)
    row.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"),
                             ("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 8)]))
    story.append(row)
    story.append(Spacer(1, 10))

    # ---- requirements ----
    story.append(P("Requirements used", "h2"))
    story.append(Spacer(1, 3))
    try:
        min_pages = int(req.get("min_pages") or 0)
    except (TypeError, ValueError):
        min_pages = 0
    if min_pages > 0:
        story.append(P(fmt(f"Minimum pages: {min_pages}"), "cell"))
    if as_list(req.get("sections")):
        story.append(P(fmt("Required sections: " + ", ".join(as_str(s) for s in as_list(req.get("sections")))), "cell"))
    if as_list(req.get("keywords")):
        story.append(P(fmt("Required keywords / technologies: " + ", ".join(as_str(s) for s in as_list(req.get("keywords")))), "cell"))
    ai_reqs = [as_str(s) for s in as_list(req.get("ai_requirements")) if as_str(s)]
    if ai_reqs:
        story.append(P("Other requirements (checked by AI; proof is quoted from the report):", "cell"))
        for i, s in enumerate(ai_reqs, 1):
            story.append(P(fmt(f"   {i}. {s}"), "cell"))
    story.append(Spacer(1, 12))

    # ---- approved ----
    story.append(heading(f"Approved ({len(approved)})"))
    if approved:
        story.append(reports_table(approved))
    else:
        story.append(P("No report met all the requirements.", "cell"))
    story.append(Spacer(1, 14))

    # ---- not approved ----
    if rejected:
        story.append(heading(f"Not approved ({len(rejected)})"))
        story.append(reports_table(rejected))
        story.append(Spacer(1, 14))

    # ---- needs review ----
    if review:
        story.append(heading(f"Needs manual review ({len(review)})"))
        story.append(Paragraph("The system could not decide these reports (for example scanned pages, unreadable files, "
                               "or a requirement the AI could not prove from the text). Please check them yourself.",
                               NOTEK))
        story.append(reports_table(review))

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=PAGE,
        leftMargin=MARGIN, rightMargin=MARGIN, topMargin=MARGIN, bottomMargin=MARGIN + 6,
        title="Project Report Review - " + assignment, author="Resume AI",
    )
    doc.build(story, onFirstPage=on_page, onLaterPages=on_page)
    return buf.getvalue()